{-# LANGUAGE OverloadedStrings #-}

module Scripts (js) where

import Data.Text (Text)
import qualified Data.Text as T

js :: Text
js =
    T.unlines
        [ "document.addEventListener('DOMContentLoaded', function() {"
        , "  var consentBanner = document.getElementById('cookie-consent');"
        , "  var consentBtn = document.getElementById('consent-btn');"
        , "  var rejectBtn = document.getElementById('reject-btn');"
        , "  var revokeBtn = document.getElementById('revoke-btn');"
        , ""
        , "  function getAllImages() {"
        , "    return document.querySelectorAll('img.lazy-consent, img.loaded');"
        , "  }"
        , ""
        , "  function loadImages() {"
        , "    getAllImages().forEach(function(img) {"
        , "      if (img.dataset.src) {"
        , "        img.src = img.dataset.src;"
        , "        img.classList.add('loaded');"
        , "        img.classList.remove('lazy-consent');"
        , "      }"
        , "    });"
        , "  }"
        , ""
        , "  function hideImages() {"
        , "    getAllImages().forEach(function(img) {"
        , "      img.removeAttribute('src');"
        , "      img.classList.remove('loaded');"
        , "      img.classList.add('lazy-consent');"
        , "    });"
        , "  }"
        , ""
        , "  var consent = localStorage.getItem('image-consent');"
        , "  if (consent === 'true') {"
        , "    loadImages();"
        , "    revokeBtn.classList.remove('hidden');"
        , "  } else if (consent === 'false') {"
        , "    revokeBtn.classList.remove('hidden');"
        , "  } else {"
        , "    consentBanner.classList.remove('hidden');"
        , "    rejectBtn.focus();"
        , "  }"
        , ""
        , "  consentBtn.addEventListener('click', function() {"
        , "    localStorage.setItem('image-consent', 'true');"
        , "    consentBanner.classList.add('hidden');"
        , "    revokeBtn.classList.remove('hidden');"
        , "    loadImages();"
        , "  });"
        , ""
        , "  rejectBtn.addEventListener('click', function() {"
        , "    localStorage.setItem('image-consent', 'false');"
        , "    consentBanner.classList.add('hidden');"
        , "    revokeBtn.classList.remove('hidden');"
        , "    hideImages();"
        , "  });"
        , ""
        , "  revokeBtn.addEventListener('click', function() {"
        , "    localStorage.removeItem('image-consent');"
        , "    revokeBtn.classList.add('hidden');"
        , "    consentBanner.classList.remove('hidden');"
        , "    hideImages();"
        , "  });"
        , "});"
        ]
